// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// mesmo ambiente web
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKqUHDXrZk-mRVzmvkpMUe6rSM1luNUMM',
    appId: '1:106851233053:web:c9626f9017bce63824c5f4',
    messagingSenderId: '106851233053',
    projectId: 'tatudobem-463bb',
    authDomain: 'tatudobem-463bb.firebaseapp.com',
    storageBucket: 'tatudobem-463bb.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKqUHDXrZk-mRVzmvkpMUe6rSM1luNUMM',
    appId: '1:106851233053:web:c9626f9017bce63824c5f4',
    messagingSenderId: '106851233053',
    projectId: 'tatudobem-463bb',
    authDomain: 'tatudobem-463bb.firebaseapp.com',
    storageBucket: 'tatudobem-463bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GUHVVwh_ppobxNmWHNVFd9jWnYQ541Y',
    appId: '1:106851233053:android:fa70e962c9dcb48224c5f4',
    messagingSenderId: '106851233053',
    projectId: 'tatudobem-463bb',
    storageBucket: 'tatudobem-463bb.appspot.com',
  );
}
